" Source system-specific configuration
if filereadable(expand('~/.dotfiles/vim/system.vim'))
  source ~/.dotfiles/vim/system.vim
endif

call plug#begin()
Plug 'NLKNguyen/papercolor-theme'
Plug 'Vimjas/vim-python-pep8-indent'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'Yggdroot/indentLine'
Plug 'airblade/vim-gitgutter'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'dag/vim-fish'
Plug 'dpelle/vim-LanguageTool'
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
Plug 'hdima/python-syntax'
Plug 'mg979/vim-visual-multi'
Plug 'patstockwell/vim-monokai-tasty'
Plug 'preservim/nerdtree'
Plug 'ryanoasis/vim-devicons'
Plug 'scrooloose/nerdcommenter'
Plug 'sjl/gundo.vim'
Plug 'tiagofumo/vim-nerdtree-syntax-highlight'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-surround'
Plug 'christoomey/vim-tmux-navigator'
" Disable default vim-tmux-navigator mappings (we'll set custom ones)
let g:tmux_navigator_no_mappings = 1
Plug 'vim-airline/vim-airline'
Plug 'jiangmiao/auto-pairs'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'sebdah/vim-delve'
Plug 'google/vim-maktaba'
Plug 'bazelbuild/vim-bazel'
call plug#end()

filetype plugin on
set encoding=utf-8

" coc.nvim configuration
" Use tab for trigger completion with characters ahead and navigate
inoremap <silent><expr> <TAB>
      \ exists('*coc#pum#visible') && coc#pum#visible() ? coc#pum#next(1) :
      \ CheckBackspace() ? "\<Tab>" :
      \ exists('*coc#refresh') ? coc#refresh() : "\<Tab>"
inoremap <expr><S-TAB> exists('*coc#pum#visible') && coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"

" Make <CR> to accept selected completion item or notify coc.nvim to format
inoremap <silent><expr> <CR> exists('*coc#pum#visible') && coc#pum#visible() ? coc#pum#confirm()
                              \: "\<C-g>u\<CR>\<c-r>=exists('*coc#on_enter') ? coc#on_enter() : ''\<CR>"

function! CheckBackspace() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

" Use <c-space> to trigger completion
inoremap <silent><expr> <c-space> coc#refresh()

" Use `[g` and `]g` to navigate diagnostics
nmap <silent> [g <Plug>(coc-diagnostic-prev)
nmap <silent> ]g <Plug>(coc-diagnostic-next)

" GoTo code navigation
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

" Use K to show documentation in preview window
nnoremap <silent> K :call ShowDocumentation()<CR>

function! ShowDocumentation()
  if exists('*CocAction') && CocAction('hasProvider', 'hover')
    call CocActionAsync('doHover')
  else
    call feedkeys('K', 'in')
  endif
endfunction

" Highlight the symbol and its references when holding the cursor
autocmd CursorHold * silent if exists('*CocActionAsync') | call CocActionAsync('highlight') | endif

" Symbol renaming
nmap <leader>rn <Plug>(coc-rename)

" Formatting selected code
xmap <leader>f  <Plug>(coc-format-selected)
nmap <leader>f  <Plug>(coc-format-selected)

" Apply AutoFix to problem on the current line
nmap <leader>qf  <Plug>(coc-fix-current)

" Show all code actions
xmap <leader>a  <Plug>(coc-codeaction-selected)
nmap <leader>a  <Plug>(coc-codeaction-selected)

" Run code action for current line
nmap <leader>ac  <Plug>(coc-codeaction-cursor)

" Show all diagnostics
nnoremap <silent><nowait> <space>d  :<C-u>CocList diagnostics<cr>
" Show outline/symbols
nnoremap <silent><nowait> <space>o  :<C-u>CocList outline<cr>
" Show commands
nnoremap <silent><nowait> <space>c  :<C-u>CocList commands<cr>

" auto-pairs configuration (if needed)
" let g:AutoPairsShortcutToggle = '<M-p>'

" python-syntax
let python_version_3 = 1
let python_highlight_all = 1

" go-vim
" Use goimports (standard tool) instead of goimports-reviser for vim
" Pre-commit hook will handle the 3-group ordering with goimports-reviser
let g:go_fmt_command = "goimports"
let g:go_fmt_autosave = 1
let g:go_def_mode='gopls'
let g:go_info_mode='gopls'
let g:go_metalinter_autosave = 0  " Disabled for performance, use :GoMetaLinter manually
let g:go_metalinter_command='golangci-lint'
let g:go_auto_type_info = 0  " Disabled, using coc.nvim for this
let g:go_doc_keywordprg_enabled = 0  " Using K with coc.nvim instead

" Bazel-specific: Don't format generated files
let g:go_fmt_experimental = 1
augroup bazel_go
  autocmd!
  " Disable auto-format for generated Go files
  autocmd BufRead,BufNewFile *.pb.go,*_generated.go setlocal nomodifiable
  autocmd BufRead,BufNewFile */bazel-*/* setlocal nomodifiable readonly
augroup END

let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_operators = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_build_constraints = 1
let g:go_highlight_generate_tags = 1

" indentLine
let g:indentLine_conceallevel = 2
let g:indentLine_concealcursor = "inc"
let g:indentLine_char = '┊'
let g:indentLine_setConceal = 2

" fzf
" Exclude Bazel-generated directories and common generated files
let $FZF_DEFAULT_COMMAND = 'rg --files --hidden --follow --glob "!.git/*" --glob "!node_modules/*" --glob "!__pycache__/*" --glob "!venv/*" --glob "!dist/*" --glob "!build/*" --glob "!bazel-*/*" --glob "!*.pb.go" --glob "!*_generated.go"'
nnoremap <C-P> :Files<CR>
nnoremap <C-B> :Buffers<CR>
nnoremap <C-F> :Rg<CR>

"nerdtree
map <C-s> :NERDTreeToggle <bar> NERDTreeMirror<CR>
autocmd BufEnter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif | AirlineRefresh
autocmd BufEnter NERD_tree* :let indentLine_enabled = 0 | AirlineRefresh
let NERDTreeShowHidden = 1
let NERDTreeMouseMode = 2
let NERDTreeDirArrowExpandable = ''
let NERDTreeDirArrowCollapsible = ''

" vim-devicons
let g:WebDevIconsNerdTreeGitPluginForceVAlign = 1
let g:WebDevIconsUnicodeDecorateFolderNodes = 1
let g:DevIconsEnableFoldersOpenClose = 1

" vim-nerdtree-syntax-highlight

let s:brown = "905532"
let s:aqua =  "3AFFDB"
let s:blue = "689FB6"
let s:darkBlue = "44788E"
let s:purple = "834F79"
let s:lightPurple = "834F79"
let s:red = "AE403F"
let s:beige = "F5C06F"
let s:yellow = "F09F17"
let s:orange = "D4843E"
let s:darkOrange = "F16529"
let s:pink = "CB6F6F"
let s:salmon = "EE6E73"
let s:green = "8FAA54"
let s:lightGreen = "31B53E"
let s:white = "FFFFFF"
let s:rspec_red = 'FE405F'
let s:git_orange = 'F54D27'

let g:WebDevIconsDefaultFolderSymbolColor = s:beige
let g:WebDevIconsDefaultFileSymbolColor = s:blue

let g:NERDTreeSyntaxDisableDefaultExtensions = 1
let g:NERDTreeSyntaxDisableDefaultExactMatches = 1
let g:NERDTreeSyntaxDisableDefaultPatternMatches = 1
let g:NERDTreeSyntaxEnabledExtensions = ['go', 'c', 'h', 'c++', 'cpp', 'py', 'rb', 'js', 'ts', 'jsx', 'tsx', 'css', 'html', 'json', 'yaml', 'yml', 'toml', 'md', 'sh', 'fish', 'bzl']
let g:NERDTreeSyntaxEnabledExactMatches = ['node_modules', 'favicon.ico', 'Makefile', 'Dockerfile', 'go.mod', 'go.sum', 'BUILD', 'WORKSPACE', 'BUILD.bazel']

" NERDTree: Ignore Bazel symlinks
let g:NERDTreeIgnore = ['^bazel-', '\.pb\.go$', '_generated\.go$']

" nerdcommenter
let NERDDefaultAlign='left'

"gundo
let g:gundo_prefer_python3 = 1
nnoremap <F5> :GundoToggle<CR>

" vim-airline
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#show_buffers = 0
let g:airline#extensions#tabline#show_splits = 1
let g:airline#extensions#coc#enabled = 1

" vim-python-pep8-indent
let g:python_pep8_indent_hang_closing = 1

" gitgutter configuration
let g:gitgutter_async = 0  " Disable async to prevent 'too many open files' error
let g:gitgutter_preview_win_floating = 0  " Use split window instead of floating
let g:gitgutter_floating_window_options = {
  \ 'relative': 'editor',
  \ 'width': &columns - 4,
  \ 'height': 15,
  \ }

"gitgutter keymappings
map ghn :GitGutterNextHunk<CR>
map ghN :GitGutterPrevHunk<CR>
map ghs :GitGutterStageHunk<CR>
map ghu :GitGutterUndoHunk<CR>
map ghp :GitGutterPreviewHunk<CR>

" Auto-configure preview window for git diffs - wrap long lines
augroup gitgutter_preview
  autocmd!
  autocmd FileType diff setlocal wrap linebreak
augroup END

function DarkTheme()
    "colorscheme sublimemonokai
    colorscheme vim-monokai-tasty
endfunction

function LightTheme()
    colorscheme shirotelin
endfunction

call DarkTheme()
set colorcolumn=80
set previewheight=20  " Make preview windows taller (for git diffs, etc)

set matchpairs=(:),{:},[:],<:>
set number
set foldcolumn=3
set updatetime=100
set foldmethod=indent
set cursorline
set statusline=_%f
set title
set mouse=a
set modifiable
set belloff=all

" Undo configuration
set undofile                      " Enable persistent undo
set undodir=$HOME/.vim/undo//     " Undo files directory
set undolevels=1000               " Maximum number of changes that can be undone
set undoreload=10000              " Maximum number lines to save for undo on buffer reload

set directory^=$HOME/.vim/tmp//

set clipboard=unnamed
set hidden  " Allow switching buffers without saving

" Terminal configuration (IDE-style terminal at bottom)
function! OpenTerminalBottom()
  botright 12split
  terminal
  startinsert
endfunction

" Open terminal in horizontal split at bottom (12 lines tall)
nnoremap <leader>tt :call OpenTerminalBottom()<CR>

" vim-tmux-navigator custom mappings (for normal mode, not terminal)
nnoremap <silent> <C-h> :TmuxNavigateLeft<CR>
nnoremap <silent> <C-j> :TmuxNavigateDown<CR>
nnoremap <silent> <C-k> :TmuxNavigateUp<CR>
nnoremap <silent> <C-l> :TmuxNavigateRight<CR>
nnoremap <silent> <C-\> :TmuxNavigatePrevious<CR>

" Terminal mode mappings
" Simple vim navigation in terminal (don't use tmux-navigator)
tnoremap <silent> <C-h> <C-\><C-n>:wincmd h<CR>
tnoremap <silent> <C-j> <C-\><C-n>:wincmd j<CR>
tnoremap <silent> <C-k> <C-\><C-n>:wincmd k<CR>
tnoremap <silent> <C-l> <C-\><C-n>:wincmd l<CR>
" Easy escape from terminal mode (enters normal mode for scrolling)
tnoremap <Esc><Esc> <C-\><C-n>
" Quick scrollback mode
tnoremap <C-s> <C-\><C-n>

" Auto-enter insert mode when switching to terminal buffer
autocmd BufEnter * if &buftype == 'terminal' | startinsert | endif

" vim hardcodes background color erase even if the terminfo file does
" not contain bce (not to mention that libvte based terminals
" incorrectly contain bce in their terminfo files). This causes
" incorrect background rendering when using a color theme with a
" background color.
let &t_ut=''
